"""
class_integration.py

Integration with CLASS Boltzmann code for validation and comparison
"""

import numpy as np
from typing import Dict, Optional, Tuple
import subprocess
import tempfile
import os

class CLASSInterface:
    """
    Interface to CLASS Boltzmann code
    
    Provides:
    - Running CLASS with quantum-corrected parameters
    - Extracting CMB and matter power spectra
    - Comparing with quantum perturbation results
    """
    
    def __init__(self, class_executable: str = "class"):
        """
        Initialize CLASS interface
        
        Parameters
        ----------
        class_executable : str
            Path to CLASS executable or just 'class' if in PATH
        """
        self.class_exe = class_executable
        self._check_class_installation()
        
    def _check_class_installation(self):
        """Check if CLASS is properly installed"""
        try:
            result = subprocess.run(
                [self.class_exe, "--version"],
                capture_output=True,
                text=True,
                check=True
            )
            print(f"CLASS version: {result.stdout.strip()}")
        except (subprocess.CalledProcessError, FileNotFoundError):
            warnings.warn(
                f"CLASS executable '{self.class_exe}' not found. "
                f"Some validation features will be disabled."
            )
            self.available = False
        else:
            self.available = True
    
    def create_parameter_file(self, params: Dict, 
                            quantum_params: Optional[Dict] = None) -> str:
        """
        Create CLASS parameter file including quantum corrections
        
        Parameters
        ----------
        params : dict
            Standard cosmological parameters
        quantum_params : dict, optional
            Quantum correction parameters
        
        Returns
        -------
        str
            Path to parameter file
        """
        # Create temporary file
        with tempfile.NamedTemporaryFile(mode='w', suffix='.ini', delete=False) as f:
            # Write standard parameters
            f.write("# CLASS parameter file with quantum corrections\n")
            f.write("# Generated by QuantumCosmologyPipeline\n\n")
            
            # Cosmological parameters
            f.write(f"output = tCl,pCl,lCl,mPk\n")
            f.write(f"H0 = {params.get('H0', 67.4)}\n")
            f.write(f"omega_cdm = {params.get('omega_cdm', 0.12)}\n")
            f.write(f"omega_b = {params.get('omega_b', 0.022)}\n")
            f.write(f"Omega_k = {params.get('Omega_k', 0.0)}\n")
            f.write(f"T_cmb = {params.get('T_cmb', 2.7255)}\n")
            f.write(f"N_eff = {params.get('N_eff', 3.046)}\n")
            f.write(f"YHe = {params.get('YHe', 0.245)}\n")
            
            # Primordial power spectrum
            f.write(f"A_s = {params.get('A_s', 2.1e-9)}\n")
            f.write(f"n_s = {params.get('n_s', 0.965)}\n")
            f.write(f"k_pivot = {params.get('k_pivot', 0.05)}\n")
            
            # Precision parameters
            f.write(f"l_max_scalars = {params.get('l_max', 2500)}\n")
            f.write(f"l_max_tensors = {params.get('l_max_tensors', 500)}\n")
            f.write(f"P_k_max_h/Mpc = {params.get('k_max', 10.0)}\n")
            f.write(f"z_max_pk = {params.get('z_max_pk', 10.0)}\n")
            
            # Quantum corrections (using CLASS extended features if available)
            if quantum_params:
                f.write("# Quantum correction parameters\n")
                f.write(f"quantum_corrections = yes\n")
                f.write(f"quantum_renormalization = {quantum_params.get('renormalization', 'adiabatic')}\n")
                f.write(f"quantum_state = {quantum_params.get('quantum_state', 'bunch_davies')}\n")
                f.write(f"quantum_alpha = {quantum_params.get('alpha', 1.0)}\n")
                f.write(f"quantum_beta = {quantum_params.get('beta', 0.0)}\n")
            
            param_file = f.name
        
        return param_file
    
    def run_class(self, param_file: str, output_dir: Optional[str] = None) -> Dict:
        """
        Run CLASS with given parameter file
        
        Parameters
        ----------
        param_file : str
            Path to CLASS parameter file
        output_dir : str, optional
            Directory for output files
            
        Returns
        -------
        dict
            CLASS results including power spectra
        """
        if not self.available:
            raise RuntimeError("CLASS is not available")
        
        if output_dir is None:
            output_dir = tempfile.mkdtemp()
        
        # Run CLASS
        cmd = [self.class_exe, param_file]
        result = subprocess.run(
            cmd,
            cwd=output_dir,
            capture_output=True,
            text=True,
            check=True
        )
        
        # Parse output
        class_results = self._parse_class_output(output_dir)
        
        # Clean up parameter file
        os.unlink(param_file)
        
        return class_results
    
    def _parse_class_output(self, output_dir: str) -> Dict:
        """Parse CLASS output files"""
        results = {}
        
        # CMB power spectra
        cl_files = {
            'TT': 'cls.dat',
            'EE': 'cls.dat',
            'TE': 'cls.dat',
            'BB': 'cls.dat',
            'PP': 'cls.dat'  # Lensing potential
        }
        
        for key, filename in cl_files.items():
            filepath = os.path.join(output_dir, filename)
            if os.path.exists(filepath):
                data = np.loadtxt(filepath)
                if key == 'TT':
                    results['ell'] = data[:, 0]
                    results['TT'] = data[:, 1]
                    results['EE'] = data[:, 2]
                    results['TE'] = data[:, 4]  # CLASS uses column 4 for TE
                elif key == 'BB' and len(data[0]) > 6:
                    results['BB'] = data[:, 6]
        
        # Matter power spectrum
        pk_file = os.path.join(output_dir, 'pk.dat')
        if os.path.exists(pk_file):
            pk_data = np.loadtxt(pk_file)
            results['k'] = pk_data[:, 0]
            results['P_k'] = pk_data[:, 1]
            results['z_pk'] = pk_data[0, 2] if pk_data.shape[1] > 2 else 0.0
        
        # Background evolution
        background_file = os.path.join(output_dir, 'background.dat')
        if os.path.exists(background_file):
            bg_data = np.loadtxt(background_file)
            results['background'] = {
                'z': bg_data[:, 0],
                'a': 1/(1 + bg_data[:, 0]),
                'H': bg_data[:, 1],
                'comoving_distance': bg_data[:, 2],
                'angular_distance': bg_data[:, 3],
                'luminosity_distance': bg_data[:, 4]
            }
        
        return results
    
    def compare_with_quantum(self, class_results: Dict, 
                           quantum_results: Dict) -> Dict:
        """
        Compare CLASS results with quantum perturbation results
        
        Parameters
        ----------
        class_results : dict
            Results from CLASS
        quantum_results : dict
            Results from quantum perturbation solver
            
        Returns
        -------
        dict
            Comparison metrics and differences
        """
        comparison = {}
        
        # Compare CMB power spectra
        if 'TT' in class_results and 'cmb_spectra' in quantum_results:
            ell = class_results['ell']
            cl_class = class_results['TT']
            
            # Interpolate quantum results to same ell values
            cl_quantum = np.interp(
                ell,
                quantum_results['cmb_spectra']['ell'],
                quantum_results['cmb_spectra']['TT']
            )
            
            # Compute differences
            diff = cl_quantum - cl_class
            rel_diff = diff / cl_class
            
            comparison['cmb_TT'] = {
                'ell': ell,
                'class': cl_class,
                'quantum': cl_quantum,
                'absolute_difference': diff,
                'relative_difference': rel_diff,
                'chi2': np.sum(diff**2 / cl_class),  # Simplified χ²
                'max_relative_difference': np.max(np.abs(rel_diff))
            }
        
        # Compare matter power spectrum
        if 'P_k' in class_results and 'scalar' in quantum_results:
            k = class_results['k']
            P_class = class_results['P_k']
            
            # Get quantum P(k)
            quantum_scalar = quantum_results['scalar']
            k_quantum = quantum_scalar['k_modes']
            P_quantum = quantum_scalar['power_spectrum']['P_matter']
            
            # Interpolate
            P_quantum_interp = np.interp(k, k_quantum, P_quantum)
            
            comparison['matter_pk'] = {
                'k': k,
                'class': P_class,
                'quantum': P_quantum_interp,
                'ratio': P_quantum_interp / P_class,
                'log_difference': np.log(P_quantum_interp) - np.log(P_class)
            }
        
        # Compute overall agreement metrics
        if 'cmb_TT' in comparison:
            # Goodness of fit
            chi2_per_dof = comparison['cmb_TT']['chi2'] / len(comparison['cmb_TT']['ell'])
            comparison['goodness_of_fit'] = {
                'chi2_per_dof': chi2_per_dof,
                'agreement_level': 'excellent' if chi2_per_dof < 0.1 else 
                                  'good' if chi2_per_dof < 1.0 else 
                                  'moderate' if chi2_per_dof < 2.0 else 'poor'
            }
        
        return comparison
